apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: team-b
  namespace: argocd
spec:
  description: Project for Team B applications

  sourceRepos:
    - https://github.com/RiteshKaushal57/Devops-Projects.git

  destinations:
    - namespace: team-b-*
      server: https://kubernetes.default.svc

  clusterResourceWhitelist:
    - group: ""
      kind: Namespace

  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
