apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:

  policy.csv: |
    # Admin role – full access
    p, role:admin, applications, *, */*, allow
    p, role:admin, projects, *, *, allow
    p, role:admin, clusters, *, *, allow
    p, role:admin, repositories, *, *, allow

    # Read-only role – view only
    p, role:readonly, applications, get, */*, allow
    p, role:readonly, projects, get, *, allow

    g, readonly, role:readonly

  policy.default: role:readonly
